import type { Metadata } from "next";
import "./globals.css";
import ModalProvider from "@/components/providers/ModalProvider";
import ChatWidget from "@/components/ui/ChatWidget";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ModalProvider>{children}</ModalProvider>
        <ChatWidget />
      </body>
    </html>
  );
}
