import type { Metadata, Viewport } from "next";
import "./globals.css";
import ModalProvider from "@/components/providers/ModalProvider";
import ChatWidget from "@/components/ui/ChatWidget";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={montserrat.variable}>
      <body className={`antialiased`}>
        <ModalProvider>
          {children}
          <ChatWidget />
        </ModalProvider>
      </body>
    </html>
  );
}
